esphome:
  name: "water-softener-sensor"

substitutions:
  # configuration values
  distance_full_in_m: 0.3
  distance_empty_in_m: 0.5
  level_low_in_percent: 10

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

logger:

api:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  # indicate wifi status via the status LED
  # - blink 3 times: wifi connected
  on_connect:
    - repeat:
        count: 3
        then:
          - switch.turn_on: led_status
          - delay: 200ms
          - switch.turn_off: led_status
          - delay: 200ms

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

switch:
  - platform: gpio
    id: led_status
    pin:
      number: GPIO2
      mode: OUTPUT
    restore_mode: ALWAYS_OFF

interval:
  # indicate overall status via status LED
  # - blink 10 times: sensor issue (no/bad value measured); sensor not working, out of range, etc.
  # - blink 5 times: low salt level detected (level_low_in_percent)
  # - blink 1 time: heartbeat signal
  - interval: 60s
    startup_delay: 30s
    then:
      - repeat:
          count: !lambda |-
            const float level = id(sensor_level).state;
            // sensor issue
            if (!std::isfinite(level)) {
              ESP_LOGD("led_status", "sensor issue -> 10");
              return 10;
            }
            // low level warning
            if (level < (${level_low_in_percent})) {
              ESP_LOGD("led_status", "salt level is low -> 5");
              return 5;
            }
            // heartbeat
            ESP_LOGD("led_status", "heartbeat -> 1");
            return 1;
          then:
            - switch.turn_on: led_status
            - delay: 200ms
            - switch.turn_off: led_status
            - delay: 200ms

sensor:
  - platform: vl53l0x
    id: sensor_distance
    name: " distance"
    address: 0x29
    update_interval: 10s
    long_range: true
    filters:
      # keep a maximum value for the distance, unless it decreases significantly
      - lambda: |-
          const float decrease_min_delta = 0.03;
          static float x_max = 0.0;
          x_max = (x > x_max || x < x_max - decrease_min_delta) ? x : x_max;
          return x_max;

  - platform: template
    id: sensor_level
    name: " level"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |-
      return id(sensor_distance).state;
    filters:
      # map distance values to 0% and 100%
      - calibrate_linear:
          method: exact
          datapoints:
            - ${distance_full_in_m} -> 100.0
            - ${distance_empty_in_m} -> 0.0
      # restrict values to the range 0% to 100%
      - clamp:
          min_value: 0
          max_value: 100
    on_value_range:
      # create a Home Assistant notification on low salt level
      - below: ${level_low_in_percent}
        then:
          - homeassistant.action:
              action: persistent_notification.create
              data:
                title: 'Water Softener'
                message: 'Salt level is low'
