esphome:
  name: "water-softener-sensor"

substitutions:
  distance_full_in_m: 0.3
  distance_empty_in_m: 0.5

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

logger:

api:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

sensor:
  - platform: vl53l0x
    id: sensor_distance
    name: " distance"
    address: 0x29
    update_interval: 10s
    long_range: true
    filters:
      - lambda: |-
          const float decrease_min_delta = 0.03;
          static float x_max = 0.0;
          x_max = (x > x_max || x < x_max - decrease_min_delta) ? x : x_max;
          return x_max;

  - platform: template
    id: sensor_level
    name: " level"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |-
      return id(sensor_distance).state;
    filters:
      - calibrate_linear:
          method: exact
          datapoints:
            - ${distance_full_in_m} -> 100.0
            - ${distance_empty_in_m} -> 0.0
      - clamp:
          min_value: 0
          max_value: 100
