esphome:
  name: "water-softener-sensor"

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

logger:

api:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

sensor:
  - platform: vl53l0x
    id: distance
    name: " distance"
    address: 0x29
    update_interval: 10s
    long_range: true
    filters:
      - median:
          window_size: 10
          send_every: 1
          send_first_at: 1

  - platform: template
    name: " level"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |-
      const float v_min = 0.30f;
      const float v_max = 0.50f;
      const float v_distance = v_max - v_min;
      float v = id(distance).state;
      if (!std::isfinite(v)) {
        return 0.0f;
      }
      float vc = std::min(std::max(v_min, v), v_max) - v_min;
      return (1.0f - (vc / v_distance)) * 100.0f;
    filters:
      - median:
          window_size: 10
          send_every: 1
          send_first_at: 1
